package com.smz.gymplus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeriodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodAllPropertiesEquals(Period expected, Period actual) {
        assertPeriodAutoGeneratedPropertiesEquals(expected, actual);
        assertPeriodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodAllUpdatablePropertiesEquals(Period expected, Period actual) {
        assertPeriodUpdatableFieldsEquals(expected, actual);
        assertPeriodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodAutoGeneratedPropertiesEquals(Period expected, Period actual) {
        assertThat(expected)
            .as("Verify Period auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodUpdatableFieldsEquals(Period expected, Period actual) {
        assertThat(expected)
            .as("Verify Period relevant properties")
            .satisfies(e -> assertThat(e.getMonthOccurrence()).as("check monthOccurrence").isEqualTo(actual.getMonthOccurrence()))
            .satisfies(e -> assertThat(e.getDayOccurrence()).as("check dayOccurrence").isEqualTo(actual.getDayOccurrence()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodUpdatableRelationshipsEquals(Period expected, Period actual) {}
}
